[project]
name = "spatial-memer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mujoco>=3.4.0",
    "numpy>=2.4.0",
    "opencv-python>=4.11.0.86",
]
